services:
  db:
    image: mysql:8.0
    container_name: exam_system_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: exam_system_passwd
      MYSQL_DATABASE: exam_system_db
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s     # Check every 10 seconds
      timeout: 5s       # Give up on a single check after 5s
      retries: 10       # Try 10 times (100 seconds total)
      start_period: 20s # DO NOT check at all for the first 20s (skips the temporary server phase)
      
  backend:
    build: ./server
    container_name: exam_system_API
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/exam_system_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=exam_system_passwd
      - Admin_passwd=admin123
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./client
    container_name: exam_system_ui
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data: